### ISSUE TITLE
builder of the active story is invoked with old state

### ISSUE THREAD

**Issue by JensHor** [firecrownpro/widgetbook#3]
# How to reproduce

1. create a story with a builder that prints, e.g. a number (1)
2. select the story (on selection the number is printed)
3. change the print of the story to another number (2)
4. hot reload the `Widgetbook`
5. observe that the old number (1) is printed instead of (2)

# Workaround 
To render the hot reloaded story, deselect the story (e.g., by selecting another story) and select the hot reloaded story again. 

# Problem
The `CanvasCubit` which provides the currently selected story does not get updated when the currently selected story is changed (and then hot reloaded). Therefore, a render (and a print) with an the old builder function is invoked.

**Comment by wwwdata** [comment]
I still have the problem that it is rendering my outdated `builder` method after a hot reload.

**Comment by JensHor** [comment]
Hello @wwwdata. thanks for your feedback. I just tested this with version `0.0.3` and it's working for me. 
My story looks like this:

```
Story(
  name: 'Default',
  builder: (context) {
    print('object 2');
    return NewTag();
  },
),
```

The widget `NewTag` is defined here https://github.com/firecrownpro/widgetbook/blob/main/packages/widgetbook/meal_app/lib/widgets/new_tag.dart 

I can either change the `print` or something within the `NewTag` widget and both changes appear either in the Debug Console or in the `widgetbook` itself.

Do you have some edge case scenario?
Can you share the code with which you are seeing the problem?

**Comment by wwwdata** [comment]
ok sorry. It is working now. My mistake was:
- I excluded the `Category` into another file as a final variable, that did not correctly reload.
- Putting it into a function that returns the `Category` works fine. So I guess this is just a Dart hot reload problem I ran into :) Everything is fine with this package then.

**Comment by JensHor** [comment]
Ok. Glad that the problem is solved. But thanks for sharing how you solved the problem. That might come in handy for other `widgetbook` users.
